# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-04 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reproductivaApp', '0009_comentariospost_id_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefonoCentroAyuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ZonasCentroAyuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.TextField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='centroayuda',
            name='direccion',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='centroayuda',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='centroayuda',
            name='google_maps',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='centroayuda',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='centroayuda',
            name='sitio_web',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telefonocentroayuda',
            name='centro_ayuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.CentroAyuda'),
        ),
        migrations.AddField(
            model_name='centroayuda',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.ZonasCentroAyuda'),
        ),
    ]
